title: D2D Toolbox
email: bilal.al-saeedi@th-koeln.de
description: A comprehensive toolbox for IWRM, REM, and NRM at ITT Th-Koeln.
baseurl: "/D2D-Toolbox" # For project sites, use the repository name
url: "https://bilal-saeedi.github.io" # Replace with your GitHub username

# Theme settings
theme: remote_theme: just-the-docs/just-the-docs
# Plugins
plugins:
  - jekyll-feed

# Navigation settings
nav:
  - title: Home
    url: /
  - title: Public Domain Data
    url: /public-domain-data/
  - title: Modules
    url: /modules/
    children:
      - title: IWRM
        url: /modules/iwrm/
        children:
          - title: Watershed
            url: /modules/iwrm/watershed/
          - title: Water and Agriculture
            url: /modules/iwrm/water-and-agriculture/
      - title: NRM
        url: /modules/nrm/
      - title: REM
        url: /modules/rem/
  - title: About
    url: /about/


# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/