title: D2D Toolbox
email: bilal.al-saeedi@th-koeln.de
description: A comprehensive toolbox for IWRM, REM, and NRM at ITT Th-Koeln.
url: "https://waterbender231.github.io"  # Base domain (no repo name)
baseurl: "/my-static-site"              # Repository name as subpath


# Theme settings

# Gem-based approach:
theme: just-the-docs

# Plugins
plugins:
  - jekyll-feed



# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/