name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/** # Only trigger on changes in the docs directory

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs # Set working directory to docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: '${{ github.workspace }}/docs'

      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site/ # Path to the built site